# Generated by Django 5.0.6 on 2024-07-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
