# Generated by Django 5.0.7 on 2024-07-26 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes_count',
        ),
    ]
