# Generated by Django 5.0.7 on 2024-08-02 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_savedpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='savedpost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
